#!/usr/bin/bash

echo " 
stty -ixon

. ${HOME}/dotfiles/history.bash
. ${HOME}/dotfiles/prompt.bash
. ${HOME}/dotfiles/aliases.bash
. ${HOME}/dotfiles/xbps.bash
. ${HOME}/dotfiles/keyboard.bash

eval \"\$(ssh-agent -s)\" &> /dev/null
ssh-add ~/.ssh/comparis_ed25519 &> /dev/null
export MANPAGER=nvimpager
" > "${HOME}/.bashrc"

echo "
.${HOME}/dotfiles/vpn.bash o
" > "${HOME}/.bash_logout"

echo "
if [ -f .bashrc ]; then . .bashrc; fi

if ! [[ \"\$PATH\" =~ \"\$HOME/.local/bin:\$HOME/bin:\" ]]; then
    PATH=\"\$HOME/.local/bin:\$HOME/bin:\$PATH\"
fi
export PATH
" > "${HOME}/.bash_profile"

