#!/usr/bin/bash

sudo xbps-install -Suy \
	base-system \
	bash-completion \
	bat \
	chromium \
	firefox \
	font-awesome \
	font-awesome5 \
	font-emoji-one-color \
	fontmanager \
	git \
	gnome-icon-theme-xfce \
	grub-x86_64-efi \
	helix \
	konsole \
	lazygit \
	lsd \
	mlocate \
	neovim \
	nodejs-lts \
	noto-fonts-emoji \
	nvimpager \
	openfortivpn \
	ppp \
	pulseaudio \
	qemu \
	slack-desktop \
	slack-term \
	sound-theme-freedesktop \
	texinfo \
	tuimoji \
	twemoji \
	unicode-emoji \
	virt-manager \
	virt-manager-tools \
	void-repo-nonfree \
	vscode \
	xclip \
	xfce4 \
	xfce4-docklike-plugin \
	xfce4-i3-workspaces-plugin \
	xfce4-panel-appmenu \
	xfce4-plugins \
	xfce4-screenshooter \
	xorg \
	xtools \
	zip \
