#!/usr/bin/env bash

_dir=$(readlink -f .)
_shebang="#!$(command -v bash)"

{
    echo -e "$_shebang"
    echo
    grep -v "^#!" "$_dir/history"
    for script in \
    "prompt"      \
    "aliases"     \
    "keyboard"    \
    ; do
        echo "source $_dir/$script"
    done
} > "bashrc"
chmod +x "$_dir/bashrc"
ln -fs "$_dir/bashrc" "${HOME}/.bashrc"

{
    echo -e "$_shebang"
    echo
    echo export MY_SCRIPTS_SRC="$_dir"
    grep -v "^#!" "$_dir/vars"
    echo
    echo source "${HOME}/.bashrc"
} > "bash_profile"
chmod +x "$_dir/bash_profile"
ln -fs "$_dir/bash_profile" "${HOME}/.bash_profile"

echo Done.
